config/routes.rb
EgeszsegvhHu::Application.routes.draw do

  resources :questions do
    resources :users
    resources :answers
  end

  resources :articles do
    resources :users
    resources :comments
  end

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  
  root :to => "home#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers

	validates :body, presence: true
	validates :answered, inclusion: { in: [true, false]}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.order('created_at desc')
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Sikeresen feltetted a kérdést!.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Kérdés frisítve.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:body, :answered)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= form_for Question.new do |f|
  .question_form
    .field
      = f.text_area :body
    .actions
      =f.submit "Küldés"

app/views/questions/edit.html.haml
= question.body
= form_for(@question) do |f|
	= f.label :answered, "Megválaszolt kérdés?"
	%br
	= f.label :answered, "Igen", :value => "true"
	= f.radio_button :answered, true
	= f.label :answered, "Nem", :value => "false"
	=f f.radio_button :answered, false
	=f.submit "Küldés"

	= link_to "Vissza", questions_path

app/views/questions/index.html.haml
.question_container
  - if user_signed_in?      
    #question_form
      %h2 Kérdezz!
      = render 'form'
  -else
    .error
      Ha új kérdést szeretnél feltenni, vagy a kérdésekre válaszolni, 
      =link_to "be kell jelentkezned!", new_user_session_path
  

  - @questions.each do |question|
    %ul
      %li
        %p= question.body
        = link_to "Tovább!", question

app/views/questions/new.html.haml
%h1 Új kérdés
= render 'form'
= link_to 'Vissza', articles_path

app/views/questions/show.html.haml
.question_container	
	.question= @question.body

	.comment_container	
		%h2 Válaszok
		- @question.answers.each do |answer|
			%ul 
				%li
					%p= answer.user		
					%p= answer.body 
		- if user_signed_in?
			= render "answers/form"
		- else
			.error
				Új válasz írásához 
				=link_to "be kell jelentkezned!", new_user_session_path
		= link_to 'Vissza', "/"