config/routes.rb
EgeszsegvhHu::Application.routes.draw do

  resources :questions do
    resources :users
    resources :answers
  end

  resources :articles do
    resources :users
    resources :comments
  end

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  
  root :to => "home#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	belongs_to :question

	validates :body, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :load_question
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.('created_at desc')
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    #@answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Sikeres hozzászólás.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to question, notice: 'Hozzászólás frissítve.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body)
    end

    def load_question
      @question = Question.find(params[:question_id])
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
= form_for([@question, @question.answers.build]) do |f|
  .comment_form
    %strong Szólj hozzá!
    %br
    = f.text_area :body
    %br
    = f.submit 'Küldés'

app/views/answers/edit.html.haml
%h1 Válasz szerkesztése

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %tr
    %th Question
    %th User
    %th Body
    %th Points
    %th Good answer
    %th
    %th
    %th

  - @answers.each do |answer|
    %tr
      %td= answer.question_id
      %td= answer.user_id
      %td= answer.body
      %td= answer.points
      %td= answer.good_answer
      %td= link_to 'Show', answer
      %td= link_to 'Edit', edit_answer_path(answer)
      %td= link_to 'Destroy', answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.haml
- @answers.each do |answer|
  = answer.body